name: Run PowerShell Script
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      run: |
        # This is where you put your PowerShell script content
        # For example, you can run a specific PowerShell script file:
        ./ImportVariablesFromFile.ps1
