name: Run PowerShell Script
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      env:
        OCTOPUS_SERVER_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        ProjectName: Terraform
        SpaceName: Default
      run: |
        # This is where you put your PowerShell script content
        # For example, you can run a specific PowerShell script file:
        #./ImportVariablesFromFile.ps1
        ./extractOctopusVariables.ps1
        
