name: Run PowerShell Script
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      env:
        OCTOPUS_SERVER_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        ProjectName: FirstProject
        SpaceName: Default
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # This is where you put your PowerShell script content
        # For example, you can run a specific PowerShell script file:
        #./ImportVariablesFromFile.ps1
        #./extractOctopusVariables.ps1 #Failed, unable to communicate
        #./extract_projectvars_json.ps1 #Failed, unable to communicate
        #./extract_projectvars.ps1 #failed, unable to communicate
        #./GetVariableInProject.ps1
        #./exportOctopusVariablesFromProject.ps1
        ./exportProjectVariable_Pattern1.ps1
        ls -lart
        # Add, commit, and push changes
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ./$outputFilePath
        git commit -m "Update variables JSON file from github actions"
        git push
        
        
