name: Run PowerShell Script
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      env:
        OCTOPUS_SERVER_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        ProjectName: FirstProject
        SpaceName: Default
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        outputVariableName: exportedVariables.json
      run: |
        # This is where you put your PowerShell script content
        # For example, you can run a specific PowerShell script file:
        #./ImportVariablesFromFile.ps1
        #./extractOctopusVariables.ps1 #Failed, unable to communicate
        #./extract_projectvars_json.ps1 #Failed, unable to communicate
        #./extract_projectvars.ps1 #failed, unable to communicate
        #./GetVariableInProject.ps1
        #./exportOctopusVariablesFromProject.ps1
        ./exportProjectVariable_Pattern1.ps1
    - name: Commit report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'puru7791@users.noreply.github.com'
        git remote set-url origin https://github.com/${GITHUB_REPOSITORY}.git
        #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git add -A
        git commit -m "Auto-generated: Extracted Octopus project variables"
        git push origin "${GITHUB_REF:11}"
    - name: Import variable to the Project
      shell: pwsh
      env: 
        destProjectName: Demo1
        OCTOPUS_SERVER_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        ProjectName: FirstProject
        SpaceName: Default
      run: |
        ./ImportVariablesFromFile.ps1