name: Import Octopus Variables

on:
  push:
    branches:
      - main

jobs:
  import_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import Variables to Octopus Deploy
      run: |
        # Replace these variables with your values
        OCTOPUS_SERVER_URL=${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY=${{ secrets.OCTOPUS_API_KEY }}
        PROJECT_ID=Projects-41
        JSON_FILE_PATH=demo-variables.json
        
        # Import variables using Octopus Deploy API
        curl -X POST "${OCTOPUS_SERVER_URL}/api/variables/$PROJECT_ID/import" \
          -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" \
          -H "Content-Type: application/json" \
          --data-binary "@${JSON_FILE_PATH}"
